databases:
  - name: ems
    plan: free
    databaseName: ems
    user: ems

services:
  - type: web
    name: ems
    plan: free
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "./bin/render-start.sh"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ems
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
